### ISSUE TITLE
Empty cluster list error

### ISSUE THREAD

**Issue by abrightwell** [will/cb#1]
When no clusters are available, I'm seeing the following error:

```
$> cb list
Unhandled exception: Empty enumerable (Enumerable::EmptyError)
  from /usr/lib/crystal/core/int.cr:1106:11 in '->'
  from /usr/lib/crystal/core/primitives.cr:255:3 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

cb: `cb v0.4.0 (202107091856)`
OS: Ubuntu 20.04

**Comment by will** [comment]
For "no clusters are available" do you mean 

1. I have clusters, but they are all offline, or creating, or whatever other not-normal state
2. I have no clusters at all

**Comment by abrightwell** [comment]
I have no clusters at all.
